"""Type stubs for resources_manager module"""

from pathlib import Path
from typing import Optional, List

def get_resource_path(resource_name: str) -> Optional[Path]: ...
def get_resource_text(resource_name: str) -> Optional[str]: ...
def get_resource_bytes(resource_name: str) -> Optional[bytes]: ...
def copy_resource_to_path(resource_name: str, destination: Path) -> bool: ...
def list_resources(directory: str = "") -> List[str]: ...
def get_git_hook(hook_name: str) -> Optional[str]: ...
def get_docker_template(template_name: str) -> Optional[str]: ...
def get_config_template(template_name: str) -> Optional[str]: ...
def get_modelfile() -> Optional[str]: ...
