from datetime import datetime
from typing import Optional, Union, Any

def utc_now() -> datetime: ...
def utc_now_iso() -> str: ...
def ensure_utc(dt: datetime) -> datetime: ...
def parse_iso_datetime(iso_string: str) -> datetime: ...
def format_iso(dt: datetime) -> str: ...
def time_ago(dt: Union[datetime, str]) -> str: ...
def add_time(dt: datetime, **kwargs: Any) -> datetime: ...

_mock_time: Optional[datetime]

def set_mock_time(dt: Optional[datetime]) -> None: ...
def utc_now_testable() -> datetime: ...

EPOCH: datetime
ISO_FORMAT: str
