from typing import Dict, Any, List

class PatternDetector:
    def __init__(self) -> None: ...
    async def detect_patterns(self, pattern_type: str) -> List[Dict[str, Any]]: ...
    async def find_bug_patterns(self, min_occurrences: int = ...) -> List[Dict[str, Any]]: ...
    async def analyze_for_dream(self) -> Dict[str, List[Dict[str, Any]]]: ...
