from typing import Dict, Any, List, Optional, Tuple

class RelationsManager:
    def __init__(self) -> None: ...
    async def get_file_dependencies(
        self, file_path: str, relation_types: Optional[List[str]] = ...
    ) -> Dict[str, List[str]]: ...
    async def find_co_modified(
        self, file_path: str, min_strength: float = ...
    ) -> List[Tuple[str, float]]: ...
    async def decay_old_relations(
        self, days_threshold: int = ..., decay_factor: float = ...
    ) -> int: ...
    async def update_metrics(self) -> None: ...
    async def find_strongest_clusters(
        self, min_nodes: int = ..., min_avg_strength: float = ...
    ) -> List[Dict[str, Any]]: ...
