from fastapi import APIRouter, Response
from typing import Dict, Any, Optional

router: APIRouter

SERVICE_START_TIME: float
_indexing_service: Optional[Any]

def get_indexing_service() -> Optional[Any]: ...
async def health_check(response: Response) -> Dict[str, Any]: ...
async def system_stats() -> Dict[str, Any]: ...
async def websocket_stats() -> Dict[str, Any]: ...
async def _check_ollama() -> Dict[str, Any]: ...
async def _check_database() -> Dict[str, Any]: ...
async def _check_embeddings() -> Dict[str, Any]: ...
async def _check_weaviate() -> Dict[str, Any]: ...
async def _check_system() -> Dict[str, Any]: ...
def _get_embeddings_suggestion(error_type: str) -> str: ...
