from typing import Optional
from typing_extensions import Literal

IDFormat = Literal["hex32", "uuid4"]

class IDGenerator:
    DEFAULT_FORMAT: IDFormat

    @staticmethod
    def generate(format: Optional[IDFormat] = ...) -> str: ...
    @staticmethod
    def to_db_format(id_str: str) -> str: ...
    @staticmethod
    def to_display_format(hex_str: str, target: IDFormat = ...) -> str: ...
    @staticmethod
    def is_valid_id(id_str: str, format: Optional[IDFormat] = ...) -> bool: ...
    @staticmethod
    def detect_format(id_str: str) -> Optional[IDFormat]: ...

def generate_id(format: Optional[IDFormat] = ...) -> str: ...
def is_valid_id(id_str: str) -> bool: ...
